<%@ Page Title="" Language="VB" MasterPageFile="~/Admin/asite.master" AutoEventWireup="false" CodeFile="mreserv.aspx.vb" Inherits="Admin_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <title>MANAGE RESERVATION</title>
    <style>
        #P {
            text-align: center;
        }
    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="body" runat="Server">

    <form id="form1" runat="server">

        <style>
            .sub_div {
                width: 150px;
                height: 100px;
                margin-left: -7%;
                position: absolute;
                display: none;
            }

                .sub_div ul li {
                    list-style-type: none;
                }

            .car_di:hover .sub_div {
                display: block;
            }
        </style>

        <!-- Header -->
        <header id="header" class="skel-layers-fixed">
            <h1><a href="astart.aspx">CAR RENTALS </a></h1>
            <nav id="nav">
                <ul>
                    <%--<li><a href="aboutus.aspx">ABOUT US</a></li>--%>
                    <%     
                        If (Session("a_id") <> "") Then
                    %>
                    <li><a href="aaccount.aspx">ACCOUNT</a></li>
                    <li class="car_di">CARS


                            <div class="sub_div">


                                <ul class="">
                                    <li style="background-color: white; width: 100px;"><a href="tcar.aspx">Add Car</a></li>
                                    <li style="background-color: white; width: 100px;"><a href="mcar.aspx">Manage Car</a></li>
                                </ul>
                            </div>




                    </li>
                    <li><a href="mreserv.aspx">RESERVATION</a></li>
                    <%
                               
                    End If
                    %>


                    <%-- <li><a href="ContactUs.aspx">CONTACT US</a></li>--%>

                    <%
                        If (Session("a_id") <> "") Then
                    %>
                    <li><a href="alogout.aspx" class="button special">Log Out</a></li>
                    <%
                    Else
                    %>
                    <li><a href="alogin.aspx" class="button special">Log In</a></li>
                    <%
           End If
        
                    %>
                </ul>
            </nav>
        </header>

        <br />
        <div class="container">

            <header class="major">
                <br />
                <br />
                <h2><strong>MANAGE RESERVATION</strong></h2>
                <hr />



            </header>


            <asp:GridView ID="gridreserv" runat="server" AutoGenerateColumns="False" CellPadding="4" DataSourceID="SqlDataSource1" ForeColor="#333333" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" GridLines="None">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                    <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                    <asp:BoundField DataField="contact" HeaderText="contact" SortExpression="contact" />
                    <asp:BoundField DataField="dedate" HeaderText="dedate" SortExpression="dedate" />
                    <asp:BoundField DataField="redate" HeaderText="redate" SortExpression="redate" />
                    <asp:BoundField DataField="ctype" HeaderText="ctype" SortExpression="ctype" />
                    <asp:BoundField DataField="cname" HeaderText="cname" SortExpression="cname" />
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>


            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:carrentalsConnection %>" SelectCommand="SELECT * FROM [reservation]"></asp:SqlDataSource>


        </div>

        <footer id="footer">
            <center>
                <div class="6u">
		
					<ul class="copyright">
						<li><strong>&copy; Car Rentals. All rights reserved.</strong></li>
						<li><strong>Design By: Shubham Ravani.</strong></li>
					<%--	<li>Images: <a href="http://unsplash.com">Google/Suport</a></li>--%>
					</ul>
				</div>
                </center>
        </footer>
    </form>

</asp:Content>

